<section class="content-header">
  <h1>
	Administrar Marcas
  </h1>
</section>

<div>
	<!-- Main content -->
	<section class="content">
	  <div class="row">
		<div class="col-xs-12">
		  <div class="box">
			<div class="box-header">
			  <h3 class="box-title">Lista de Marcas</h3>
			  <button class="btn btn-primary" id="btn-register" style="float: right;">Cadastrar</button>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
			  <table id="table-data" class="table table-bordered table-hover">
				<thead>
				<tr>
				  <th>Nome</th>
				  <th>Ativa</th>
				  <th>Data de Cadastro</th>
				</tr>
				</thead>
				<tbody>
				  <?php
				  if(!empty($this->data)):
					foreach ($this->data as $key => $value):
				  ?>
				  <tr>
					  <td><?php echo $value['name'];?></td>
					  <td><?php echo $value['active'];?></td>
					  <td><?php echo date("d/m/Y H:i:s", strtotime($value['date_register']));?></td>
				  </tr>
				<?php
				  endforeach;
				endif;
				?>
				</tbody>
			  </table>
			</div>
			<!-- /.box-body -->
		  </div>
		  <!-- /.box -->
		</div>
		<!-- /.col -->
	  </div>
	  <!-- /.row -->

        <div class="modal fade" id="modal-default">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              	</button>
                <h4 class="modal-title" id="title-modal">Editar Marca</h4>
              </div>
              <div class="modal-body">
              	<div class="text-center" id="modal-div-loading">
                	<img src="/img/loading-medium.gif">
              	</div>

              	<div id="modal-div-form">
	              	<!-- form start -->
		            <form role="form">
		              <div class="box-body">
		                <div class="form-group col-lg-7">
		                  <label for="inp-name">Nome</label>
		                  <input type="text" class="form-control" id="inp-name" placeholder="Enter name">
		                </div>
		                <br>
		                <div class="checkbox col-lg-5">
		                  <label>
		                    <input type="checkbox" id="chk-active"> Ativo
		                  </label>
		                </div>
		              </div>
		              <!-- /.box-body -->
		            </form>

              	</div>


              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" id="btn-save">Salvar alterações</button>
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->

	</section>
	<!-- /.content -->
</div>

<!-- page script -->
<!-- DataTables -->
<?php
  	echo $this->headScript()
            ->prependFile($this->basePath() . '/js/page-mark.js')
            ->prependFile($this->basePath() . '/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')
            ->prependFile($this->basePath() . '/bower_components/datatables.net/js/jquery.dataTables.min.js')
?>