<section class="content-header">
  <h1>
	Administrar Marcas
  </h1>
</section>

<div>
	<!-- Main content -->
	<section class="content">
	  <div class="row">
		<div class="col-xs-12">
		  <div class="box">
			<div class="box-header">
			  <h3 class="box-title">Lista de Marcas</h3>
			  <button class="btn btn-primary" id="btn-register" style="float: right;">Cadastrar</button>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
			  <table id="table-data" class="table table-bordered table-hover">
				<thead>
				<tr>
				  <th>Nome</th>
				  <th>Ativa</th>
				  <th>Data de Cadastro</th>
				</tr>
				</thead>
				<tbody>
				  <?php
				  if(!empty($this->data)):
					foreach ($this->data as $key => $value):
				  ?>
				  <tr>
					  <td><?php echo $value['name'];?></td>
					  <td><?php echo $value['active'];?></td>
					  <td><?php echo date("d/m/Y H:i:s", strtotime($value['date_register']));?></td>
				  </tr>
				<?php
				  endforeach;
				endif;
				?>
				</tbody>
			  </table>
			</div>
			<!-- /.box-body -->
		  </div>
		  <!-- /.box -->
		</div>
		<!-- /.col -->
	  </div>
	  <!-- /.row -->

        <div class="modal fade" id="modal-default">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              	</button>
                <h4 class="modal-title" id="modal-title">Editar Marca</h4>
              </div>
              <div class="modal-body">
              	<div id="modal-div-form">
	              	<!-- form start -->
		            <form id="form-data" role="form" onsubmit="return false;">
		              <div class="box-body">
		                <div class="form-group col-lg-7">
		                  <label for="inp-name">Nome</label>
		                  <input type="text" class="form-control" id="inp-name" placeholder="Enter name" data-error="Este campo não pode ser vazio" required>
		                  <div class="help-block with-errors"></div>
		                </div>
		                <br>
		                <div class="checkbox col-lg-5">
		                  <label>
		                    <input type="checkbox" id="chk-active"> Ativo
		                  </label>
		                </div>
		              </div>
		              <!-- /.box-body -->

              	</div>


              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                <div class="form-group">
                	<button type="submit" class="btn btn-primary">Salvar alterações</button>
            	</div>
              </div>

	            	</form>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->

	</section>
	<!-- /.content -->
</div>

<!-- page script and css -->
<!-- DataTables -->
<?php
  	//echo
  	$this->headScript()
            ->prependFile($this->basePath() . '/js/page-mark.js')
  			->prependFile($this->basePath() . '/js/bootstrap-validator.min.js')
            ->prependFile($this->basePath() . '/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')
            ->prependFile($this->basePath() . '/bower_components/datatables.net/js/jquery.dataTables.min.js');
            $this->headLink()->prependStylesheet($this->basePath() . '/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css');
?>